version: '3'

services: 
  frontend:
    image: devopscsaos_frontend
    build: ./frontend
    ports: 
      - 3000:3000
  backend:
    image: devopscsaos_backend
    build: ./backend
    ports: 
      - 5000:5000
    environment: 
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    depends_on: 
      - dev_db
  dev_db:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
