version: '3.1'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    expose:
      - 5432
    ports:
      - 5400:5432

  surveybackend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        API_URL: http://localhost:5000/
    image: devopscsaosback
    command: bash -c "sleep 5s && node ./backend/server.js"
    environment:
      API_URL: http://localhost:5000/
      NODE_ENV: development
      DB_HOST: postgres-db
      PORT: 5000
      DB_USER: testUser
      DB_PASS: password
      SECRET_FOR_TOKEN: supersecretfore2etests
    volumes:
      - "/Users/juusotamminen/Desktop/devops csaos survey/DevOpsCSAOS/"
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - postgres-db

  surveyfrontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        PORT: 3000
        API_URL: http://localhost:5000/
        NODE_ENV: development
    image: devopscsaosfront
    environment:
      API_URL: http://localhost:5000/
      NODE_ENV: development
      PORT: 3000
      SECRET_FOR_TOKEN: supersecretfore2etests
    volumes:
      - "/Users/juusotamminen/Desktop/devops csaos survey/DevOpsCSAOS/"
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - surveybackend
