version: '3.8'

services:
  postgres-db:
    image: postgres:13-alpine
    tty: true
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: endtoend_test_db
    ports:
      - 5400:5432

  devopscsaos:
    build:
      context: ../backend
    command: ./wait-for  postgres-db:5432 -- npm run dev
    tty: true
    environment:
      NODE_ENV: endtoend
      PORT: 5001
      DB_HOST: postgres-db
      DB_USER: testUser
      DB_PASS: password
      SECRET_FOR_TOKEN: supersecretfore2etests
    ports:
      - 5001:5001
    depends_on:
      -  postgres-db
      
  frontend:
    build:
      context: ../frontend
    tty: true
    environment:
      API_URL: http://localhost:5001/api
      NODE_ENV: development

    ports:
      - 3000:3000

