version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: endtoend_test_db
    expose:
      - 5432
    ports:
      - 5432:5432

  devopscsaos:
    build:
      context: ../
      dockerfile: ./Dockerfile
      args: 
        API_URL: http://localhost:5001
    image: devopscsaos
    environment: 
      API_URL: http://localhost:5001
      NODE_ENV: endtoend
      DB_HOST: postgres-db
      DB_USER: testUser
      DB_PASS: password
    ports:
      - 5001:5001
    depends_on: 
      - postgres-db



