version: '3.1'

services:
  postgres-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: endtoend_test_db
    expose:
      - 5432
    ports:
      - 5400:5432

  devopscsaos:
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        API_URL: http://localhost:5001/api
    image: devopscsaos
    command: bash -c "sleep 5s && node ./backend/server.js"
    environment:
      API_URL: http://localhost:5001/api
      NODE_ENV: endtoend
      DB_HOST: postgres-db
      DB_USER: testUser
      DB_PASS: password
      SECRET_FOR_TOKEN: supersecretfore2etests
    ports:
      - 5001:5001
    depends_on:
      - postgres-db
