version: '3.1'

services:
  postgres-test-db:
    image: postgres
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    expose:
      - 5432

  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    image: backend
    expose:
      - 5000
    environment: 
      NODE_ENV: test
      DB_HOST: postgres-test-db
      DB_USER: testUser
      DB_PASS: password
    ports:
      - 5000:5000
    depends_on: 
      - postgres-test-db


  frontend:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    image: frontend
    environment:
      HOST: http://frontend:3000
      BACKEND_URL: http://backend:5000
      NODE_ENV: test
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on: 
      - backend


