name: Deploy

on: [push]

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run backend tests
        working-directory: ./backendv2
        run: npm install && npm test
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm install && npm test
      - name: Test image building
        run: docker build . -t image-test-build

  deploy_to_staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ohtu-csaos-staging" 
          heroku_email: ${{secrets.PROJECT_EMAIL}}
          usedocker: true

