name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run backend tests
        working-directory: ./backendv2
        run: npm install && npm test
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm install && npm test
      - uses: akhileshns/heroku-deploy@v3.8.9 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ohtu-staging" 
          heroku_email: "ossi.j.lehtonen@helsinki.fi"
          usedocker: true
