name: Deploy

on: [push]

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Run backend tests
        working-directory: ./backend
        run: npm install && npm run sequalize:migrate && npm test
        env:
          DB_HOST: localhost
          DB_PASS: postgres
          DB_USER: postgres
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm install && npm test
      - name: Run backend lint
        working-directory: ./backend
        run: npm run lint
      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint
      - name: Test image building
        run: docker build . -t image-test-build

  deploy_to_staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ohtu-csaos-staging'
          heroku_email: ${{secrets.PROJECT_EMAIL}}
          usedocker: true
